function enableFields(form) { 
    var activity = getValue('WKNumState');
    form.setEnabled("destino", false);
    form.setEnabled("obs", false);
    
    if (form.getFormMode() != 'ADD'){  
        form.setEnabled("nomeSolicitante",  false);
        form.setEnabled("departamentos",    false);
        form.setEnabled("chapaSolicitante", false);
        form.setEnabled("email", 			false);
        form.setEnabled("unidades",         false);
        form.setEnabled("checkbox1", 		false);
        form.setEnabled("checkbox2", 		false);
        form.setEnabled("checkbox3", 		false);
        form.setEnabled("checkbox4", 		false);
        form.setEnabled("checkbox5", 		false);
        form.setEnabled("checkbox6", 		false);
        form.setEnabled("checkbox7", 		false);
        form.setEnabled("checkbox8", 		false);
        form.setEnabled("checkbox9", 		false);
        form.setEnabled("checkbox10", 		false);
        form.setEnabled("checkbox11", 		false);
        form.setEnabled("checkbox12", 		false);
        form.setEnabled("checkbox13", 		false);
        form.setEnabled("checkbox14", 		false);
        form.setEnabled("outrosCateg", 		false);
        form.setEnabled("cargoSolicitado", 	false);
        form.setEnabled("departamentosReq", false);
        form.setEnabled("tipoContrat", 		false);
        form.setEnabled("e1", 				false);
        form.setEnabled("s1", 				false);
        form.setEnabled("e2", 				false);
        form.setEnabled("s2", 				false);
        form.setEnabled("motivoRequisicao", false);
        form.setEnabled("justificativaAumentoQuadro", 		false);
        form.setEnabled("justificativaSubstituicao", 		false);
        form.setEnabled("nomeSubstituido", 	false);
        form.setEnabled("saidaSubstituido", false);
        form.setEnabled("idade", 			false);
        form.setEnabled("outrosIdade", 		false);
        form.setEnabled("sexo", 			false);
        form.setEnabled("escolaridade", 	false);
        form.setEnabled("periodo", 			false);
        form.setEnabled("cursos", 			false);
        form.setEnabled("estadoCivil", 		false);
        form.setEnabled("habilitacao", 		false);
        form.setEnabled("outrosHab", 		false);
        form.setEnabled("veiculoProprio", 	false);
        form.setEnabled("comportamental", 	false);
        form.setEnabled("tecnica", 			false);
        form.setEnabled("outrasInfo", 		false);
        form.setEnabled("remuneracao", 		false);
        form.setEnabled("variavel", 		false);
        form.setEnabled("tipoVariavel", 	false);
        form.setEnabled("condicoesVariavel",false);
        form.setEnabled("recrutamento", 	false);
        form.setEnabled("sugestao", 		false);
        form.setEnabled("dataAdmissao", 	false);
        form.setEnabled("gerente", 			false);
    }
    if (activity == 11){
        form.setEnabled("nomeSolicitante",  true);
        form.setEnabled("departamentos",    true);
        form.setEnabled("chapaSolicitante", true);
        form.setEnabled("email", 			true);
        form.setEnabled("unidades",         true);
        form.setEnabled("checkbox1", 		true);
        form.setEnabled("checkbox2", 		true);
        form.setEnabled("checkbox3", 		true);
        form.setEnabled("checkbox4", 		true);
        form.setEnabled("checkbox5", 		true);
        form.setEnabled("checkbox6", 		true);
        form.setEnabled("checkbox7", 		true);
        form.setEnabled("checkbox8", 		true);
        form.setEnabled("checkbox9", 		true);
        form.setEnabled("checkbox10", 		true);
        form.setEnabled("checkbox11", 		true);
        form.setEnabled("checkbox12", 		true);
        form.setEnabled("checkbox13", 		true);
        form.setEnabled("checkbox14", 		true);
        form.setEnabled("outrosCateg", 		true);
        form.setEnabled("cargoSolicitado", 	true);
        form.setEnabled("departamentosReq", true);
        form.setEnabled("tipoContrat", 		true);
        form.setEnabled("e1", 				true);
        form.setEnabled("s1", 				true);
        form.setEnabled("e2", 				true);
        form.setEnabled("s2", 				true);
        form.setEnabled("motivoRequisicao", true);
        form.setEnabled("justificativaAumentoQuadro", 		true);
        form.setEnabled("justificativaSubstituicao", 		true);
        form.setEnabled("nomeSubstituido", 	true);
        form.setEnabled("saidaSubstituido", true);
        form.setEnabled("idade", 			true);
        form.setEnabled("outrosIdade", 		true);
        form.setEnabled("sexo", 			true);
        form.setEnabled("escolaridade", 	true);
        form.setEnabled("periodo", 			true);
        form.setEnabled("cursos", 			true);
        form.setEnabled("estadoCivil", 		true);
        form.setEnabled("habilitacao", 		true);
        form.setEnabled("outrosHab", 		true);
        form.setEnabled("veiculoProprio", 	true);
        form.setEnabled("comportamental", 	true);
        form.setEnabled("tecnica", 			true);
        form.setEnabled("outrasInfo", 		true);
        form.setEnabled("remuneracao", 		true);
        form.setEnabled("variavel", 		true);
        form.setEnabled("tipoVariavel", 	true);
        form.setEnabled("condicoesVariavel",true);
        form.setEnabled("recrutamento", 	true);
        form.setEnabled("sugestao", 		true);
        form.setEnabled("dataAdmissao", 	true);
        form.setEnabled("gerente", 			true);
    }
    if (activity == 5){
        form.setEnabled("destino", 			true);
        form.setEnabled("obs", 				true);
    }
    
}